name: TasoZoroudis
favicon: null
layout_spectrum: 0.3640126946847886
typography_spectrum: 0.9881278863176703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7848043751437217
  lightness: 0.03625485999509692
  saturation: 0.61633679154329
  rhythmicContrast: 0.49410686758346856
purpose: []
